BlogProject/BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BlogProject/blog_app/urls.py
from django.urls import path
from . import views

app_name = 'blog_app'

urlpatterns = [
    
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug:slug>/', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('myblogs/', views.MyBlogs.as_view(), name='myblogs'),
    path('edit/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
]

BlogProject/login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),   
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change_profile/', views.user_change, name='change_profile'),
    path('password/', views.pass_change, name='change_password'),
    path('add_profile_picture/', views.add_profile_picture, name='add_picture'),
    path('change_profile_picture/', views.change_profile_picture, name='change_picture'),
    path('edit_bio/', views.edit_bio, name='edit_bio'),
]

BlogProject/login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='user_profile_pictures')
    about = models.TextField(max_length=101, default=' ')

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name
    

BlogProject/login_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import UserProfile

class SignUpForm(UserCreationForm):
    email = forms.EmailField(label='Email Address', required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class UserProfileChange(UserChangeForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')

# This form is used to change the user profile picture 
class ProfilePicture(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_picture',]

class EditBio(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['about',]

BlogProject/login_app/views.py
from django.shortcuts import render
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm, UserProfileChange, ProfilePicture, EditBio
# Create your views here.

def sign_up(request):
    form = SignUpForm()

    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            
            return HttpResponseRedirect(reverse('login_app:login'))
        
    dict = {'form': form,}

    return render(request, 'login_app/signup.html', dict)

def login_page(request):
    form  = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
                
    
    return render(request, 'login_app/login.html', context={'form': form})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required 
def profile(request):
    return render(request, 'login_app/profile.html', {})

@login_required 
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)
            return HttpResponseRedirect(reverse('login_app:profile'))
    return render(request, 'login_app/change_profile.html', {'form': form})

@login_required 
def pass_change(request):
    changed = False
    current_user = request.user
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'login_app/change_password.html', {'form': form, 'changed': changed })

@login_required 
def add_profile_picture(request):
    form = ProfilePicture()
    if request.method == 'POST':
        form = ProfilePicture(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('login_app:profile'))
    return render(request, 'login_app/add_profile_picture.html', {'form': form})

@login_required 
def change_profile_picture(request):
    form = ProfilePicture(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePicture(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('login_app:profile'))
    return render(request, 'login_app/add_profile_picture.html', {'form': form, 'change': True})

@login_required 
def edit_bio(request):
    form = EditBio(instance=request.user.user_profile)
    if request.method == 'POST':
        form = EditBio(request.POST, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('login_app:profile'))
    return render(request, 'login_app/edit_bio.html', {'form': form,})

BlogProject/templates/login_app/add_profile_picture.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title_block %} Profile picture {% endblock %}
{% block body_block %}

<div class="container pt-4">
    <div class="row">
        <div class="col-md-4">
            {% if change %}
            <h4 class="text-primary">Change Profile Picture</h4>
            {% else %}
            <h4 class="text-primary">Add Profile Picture</h4>
            {% endif %}
            <form method="POST" enctype="multipart/form-data">
                <div class="form-group">
                    <img src="/media/{{user.user_profile.profile_picture}}" alt="user profile picture" width="100%" height="auto">
                    {{form|crispy}}
                    {% csrf_token%}
                </div>
                <button type="submit" class="btn btn-primary btn-sm">Save</button>
            </form><br>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-6">
            <img src="{% static 'images/The_Developers.png' %}" width="100%" height="auto" alt="The Developers Banner"
                style="aspect-ratio: auto;">
        </div>
    </div>
</div>

{% endblock %}

BlogProject/templates/login_app/change_password.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title_block %} Change Password {% endblock %}
{% block body_block %}
{% if changed %}
<div class="alert alert-success">Your password has been changed successfully!</div>
{% else %}
<div class="container pt-4">
    <div class="row">
        <div class="col-md-10">
            <h4 class="text-primary">Change Your Password</h4>

            <form method="POST">
                <div class="form-group">
                    {{form|crispy}}
                    {% csrf_token%}
                </div>
                <button type="submit" class="btn btn-primary btn-sm">Save</button>
            </form><br>

        </div>
        <div class="col-md-2">
            <img src="{% static 'images/The_Developers.png' %}" width="100%" height="auto" alt="The Developers Banner"
                style="aspect-ratio: auto;">
        </div>
    </div>
</div>

{% endif %}
{% endblock %}

BlogProject/templates/login_app/change_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title_block %} Change Profile {% endblock %}
{% block body_block %}

<div class="container pt-4">
    <div class="row">
        <div class="col-md-10">
            <h4 class="text-primary">Change Account Information</h4>

            <form method="POST">
                <div class="form-group">
                    {{form|crispy}}
                    {% csrf_token%}
                </div>
                <button type="submit" class="btn btn-primary btn-sm">Save</button>
            </form><br>

        </div>
        <div class="col-md-2">
            <img src="{% static 'images/The_Developers.png' %}" width="100%" height="auto" alt="The Developers Banner"
                style="aspect-ratio: auto;">
        </div>
    </div>
</div>


{% endblock %}

BlogProject/templates/login_app/edit_bio.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title_block %} Edit bio {% endblock %}
{% block body_block %}

<div class="container pt-4">
    <div class="row">
        <div class="col-md-4">
            <h4 class="text-primary">Edit Bio</h4>
            <form method="POST">
                <div class="form-group">
                    {{form|crispy}}
                    {% csrf_token %}
                    <small><span class="text-info">Describe yoouself. (Max character: 101)</span></small>
                </div>
                <button type="submit" class="btn btn-primary btn-sm">Save</button>
            </form><br>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-6">
            <img src="{% static 'images/The_Developers.png' %}" width="100%" height="auto" alt="The Developers Banner" style="aspect-ratio: auto;">
        </div>
    </div>
</div>

{% endblock %}

BlogProject/templates/login_app/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block title_block %} Login {% endblock %}
{% block body_block %}


<div class="container pt-4">
    <div class="row">
        <div class="col-md-6">
            <h4 class="text-primary">Login with Your Acoount</h4>

            <form method="POST">
                <div class="form-group">
                    {{form|crispy}}
                    {% csrf_token %}
                </div>
                <button type="submit" class="btn btn-primary btn-sm">Login</button>
            </form><br>
        </div>
        <div class="col-md-6">
            <img src="{% static 'images/The_Developers.png' %}" width="100%" height="auto" alt="The Developers Banner" style="aspect-ratio: auto;">
        </div>
    </div>
</div>

{% endblock %}

BlogProject/templates/login_app/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title_block %} Profile {% endblock %}
{% block body_block %}


<div class="container pt-4">
  <div class="row">
    <div class="col-md-4">
      <h4 class="text-primary">Your Profile</h4>
      <div class="card mb-3" style="width: 18rem;">
        {% if user.user_profile %}
        <img src="/media/{{user.user_profile.profile_picture}}" width="100%" height="auto" class="card-img-top"
          alt="user image"> <br>
        <a href="{% url 'login_app:change_picture' %}" class="btn btn-info btn-sm">Change profile picture</a>
        {% else %}
        <img src="/media/user_profile_pictures/unisex_avatar.jpg" width="100%" height="auto" class="card-img-top"
          alt="user image">
        <a href="{% url 'login_app:add_picture' %}" class="btn btn-info btn-sm">Add profile picture</a>
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">@{{user.username}} <a href="{% url 'login_app:change_profile' %}"
              class="card-link btn btn-primary btn-sm">Edit Profile</a></h5>
          {% if user.user_profile%}
          <p class="card-text">{{user.user_profile.about}}</p>
          <a href="{% url 'login_app:edit_bio' %}" class="btn btn-info btn-sm">Edit Bio</a>
          {% endif %}
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><strong>Name: </strong>{{user.first_name}} {{user.last_name}}</li>
          <li class="list-group-item"><strong>Email: </strong>{{user.email}}</li>
        </ul>
        <div class="card-body">
          <a href="#" class="card-link">Facebook</a>
          <a href="#" class="card-link">LinkedIn</a>
        </div>
      </div>
    </div>
    <div class="col-md-2"></div>
        <div class="col-md-6">
            <img src="{% static 'images/The_Developers.png' %}" width="100%" height="auto" alt="The Developers Banner" style="aspect-ratio: auto;">
        </div>
  </div>
</div>

{% endblock %}

BlogProject/templates/login_app/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block title_block %} Sign Up {% endblock %}
{% block body_block %}

<div class="container pt-4">
    <div class="row">
        <div class="col-md-6">
            <h4 class="text-primary">Create New Account</h4>

    <form method="POST">
        <div class="form-group">
            {{form|crispy}}
            {% csrf_token%}
        </div>
        <button type="submit" class="btn btn-primary btn-sm">Sign up</button>
    </form><br>
    
    <p><span class="alert alert-primary">Already have an account? <a href="{% url 'login_app:login' %}">Login here</a></span></p>
        </div>
        <div class="col-md-6">
            <img src="{% static 'images/The_Developers.png' %}" width="100%" height="auto" alt="The Developers Banner" style="aspect-ratio: auto;">
        </div>
    </div>
</div>

{% endblock %}