BlogProject/BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BlogProject/blog_app/urls.py
from django.urls import path
from . import views

app_name = 'blog_app'

urlpatterns = [
    
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug:slug>/', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('myblogs/', views.MyBlogs.as_view(), name='myblogs'),
    path('edit/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
]

BlogProject/blog_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=255, verbose_name="Put a title")
    slug = models.SlugField(max_length=255, unique=True)
    blog_content = models.TextField(verbose_name="What's on your mind?")
    blog_image = models.ImageField(upload_to='blog_images', verbose_name='Image')
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-publish_date', ]

    def __str__(self):
        return self.blog_title

    def save(self):
        self.slug = slugify(self.blog_title)
        super(Blog, self).save()

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-comment_date', ]

    def __str__(self):
        return self.comment

class Like(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='liked_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liked_user')

    def __str__(self):
        return str(self.user) + " likes " + str(self.blog)

BlogProject/blog_app/forms.py
from django import forms
from .models import Blog, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

BlogProject/blog_app/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, ListView, DetailView, View, TemplateView, DeleteView
from .models import Blog, Comment, Like
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
from .forms import CommentForm

# Create your views here.

class MyBlogs(LoginRequiredMixin, TemplateView):
    template_name = 'blog_app/myblogs.html'


class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'blog_app/blog_list.html'
    

class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'blog_app/create_blog.html'
    fields = ('blog_title', 'blog_content', 'blog_image')

    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace('\' ', '-')
        blog_obj.slug = title.replace(' ', '-') + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))

@login_required
def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)
    comment_form = CommentForm()
    already_liked = Like.objects.filter(blog=blog, user=request.user)
    if already_liked:
        liked = True
    else: liked = False
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('blog_app:blog_details', kwargs={'slug': slug}))

    return render(request, 'blog_app/blog_details.html', {'blog': blog, 'comment_form': comment_form, 'liked': liked})
    
@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(blog=blog, user=user)
    if not already_liked:
        liked_post = Like(blog=blog, user=user)
        liked_post.save()
    
    return HttpResponseRedirect(reverse('blog_app:blog_details', kwargs={'slug':blog.slug}))

@login_required
def unliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('blog_app:blog_details', kwargs={'slug':blog.slug}))

class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name = 'blog_app/edit_blog.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('blog_app:blog_details', kwargs={'slug':self.object.slug})

BlogProject/templates/blog_app/blog_details.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block body_block %}

<div class="blog-container">
    <div class="container">
        <div class="row pt-5">
            <div class="col">
                <h2 class="text-primary">{{blog.blog_title}}</h2>
                <p><strong>@{{blog.author}},</strong><small class="text-muted"> {{blog.publish_date}}</small><br>

                <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} Comments</h6>
                </p>
                <img src="/media/{{blog.blog_image}}" height="300px" class="rounded mx-auto d-block" width="700px" alt="Blog Image">
                <p>{{blog.blog_content|linebreaks}}</p>
            </div>
        </div>
        <hr>
        {% if not liked %}
        <a href="{% url 'blog_app:liked_post' pk=blog.pk %}">
            <i class="fa fa-thumbs-o-up fa-2x" aria-hidden="true"></i>
        </a>
        {% else %}
        <a href="{% url 'blog_app:unliked_post' pk=blog.pk %}">
            <i class="fa fa-thumbs-o-down fa-2x" aria-hidden="true"></i>
        </a><br><small>You like this blog</small>
        {% endif %}
        <div class="row pt-3">
            <div class="col-sm-6">
                <strong>Comments: </strong>
                {% for comment in blog.blog_comment.all %}
                <p><strong class="text-info">@{{comment.user}}</strong> {{comment}}<br>
                    <small class="text-muted">{{comment.comment_date}}</small></p>
                {% endfor %}
            </div>
            <div class="col-sm-6">
                <form method="POST">
                    <div class="form-group">
                        {{comment_form|crispy}}
                        {% csrf_token%}
                    </div>
                    <button type="submit" class="btn btn-primary btn-sm">Comment</button>
                </form><br>
            </div>
        </div>
    </div>
</div>

{% endblock %}

BlogProject/templates/blog_app/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} Home {% endblock %}
{% block body_block %}

<h3 class="text-center pt-4">Available Blogs</h3>

<div class="blog-container">
    <div class="container">
        <div class="row mb-2 pt-5">
            {% for blog in blogs %}
            <div class="col-md-6">
                <div
                    class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-primary">@{{blog.author}}</strong>
                        <h6 class="mb-0 text-primary">{{blog.blog_title}}</h6>
                        <div class="text-muted">{{blog.publish_date}}</div>
                        <p class="card-text ">{{blog.blog_content|range_filter|linebreaks}}</p>
                        <a href="{% url 'blog_app:blog_details' slug=blog.slug %}" class="stretched-link">Continue
                            reading</a><br>
                            <small>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count }} Comments </small>
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <img src="/media/{{blog.blog_image}}" alt="Blog Image" width="250" height="300">
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

BlogProject/templates/blog_app/create_blog.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title_block %} Write your blog {% endblock %}
{% block body_block %}

<div class="container pt-4">
    <div class="row">
        <div class="col-md-6">
            <h4 class="text-primary">Write your BLOG here</h4>

            <form method="POST" enctype="multipart/form-data">
                <div class="form-group">
                    {{form|crispy}}
                    {% csrf_token%}
                </div>
                <button type="submit" class="btn btn-primary btn-sm">Publish</button>
            </form><br>

        </div>
        <div class="col-md-6">
            <img src="{% static 'images/The_Developers.png' %}" width="100%" height="auto" alt="The Developers Banner"
                style="aspect-ratio: auto;">
        </div>
    </div>
</div>

{% endblock %}

BlogProject/templates/blog_app/edit_blog.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block body_block %}
{% if blog.author == user %}
<div class="container pt-4">
    <div class="row">
        <div class="col-md-6">
            <h4 class="text-primary">Write your BLOG here</h4>

            <form method="POST" enctype="multipart/form-data">
                <div class="form-group">
                    {{form|crispy}}
                    {% csrf_token%}
                </div>
                <button type="submit" class="btn btn-primary btn-sm">Update</button>
            </form><br>

        </div>
        <div class="col-md-6">
            <img src="{% static 'images/The_Developers.png' %}" width="100%" height="auto" alt="The Developers Banner"
                style="aspect-ratio: auto;">
        </div>
    </div>
</div>
{% else %}
<div class="alert-alert-danger">You are not allowed to edit this page!</div>
{% endif %}
{% endblock %}

BlogProject/templates/blog_app/myblogs.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load custom_filters %}
{% block title_block %} My blogs {% endblock %}
{% block body_block %}

{% for blog in user.post_author.all %}

<div class="blog-container pt-5">
    <div class="container">
        <h3>{{blog.blog_title}}</h3>
        <h6>{{blog.publish_date}}</h6>
        <div class="row">
            <div class="col-sm-4">
                <img src="/media/{{blog.blog_image}}" width="100%">
            </div>
            <div class="col-sm-8">
                <p>{{blog.blog_content|range_filter|linebreaks}}</p>
                <a href="{% url 'blog_app:blog_details' slug=blog.slug %}">Read More</a>
            </div>
        </div>
        <a href="{% url 'blog_app:edit_blog' pk=blog.pk %}">Edit</a>
        <hr>
    </div>
</div>


{% endfor %}
{% endblock %}